apiVersion: v1
kind: Secret
metadata:
  name: profile-security
  namespace: profile-ms
type: Opaque
stringData:
  BASIC_AUTH_USER: REPLACE_WITH_BASIC_AUTH_USER
  BASIC_AUTH_PASSWORD: REPLACE_WITH_STRONG_BASIC_AUTH_PASSWORD
  KEY_PAIR_ID: REPLACE_WITH_KEY_PAIR_ID
  KEY_PAIR_SECRET: REPLACE_WITH_STRONG_KEY_PAIR_SECRET
  TOKEN_SECRET: REPLACE_WITH_STRONG_TOKEN_SECRET
